debian/neutron_sudoers etc/sudoers.d
etc/api-paste.ini etc/neutron
etc/dhcp_agent.ini etc/neutron
etc/l3_agent.ini etc/neutron
etc/metadata_agent.ini etc/neutron
etc/metering_agent.ini etc/neutron
etc/neutron.conf etc/neutron
etc/neutron/plugins/ml2/linuxbridge_agent.ini
etc/neutron/plugins/ml2/macvtap_agent.ini
etc/neutron/plugins/ml2/ml2* etc/neutron/plugins/ml2
etc/neutron/plugins/ml2/openvswitch_agent.ini
etc/neutron/plugins/ml2/sriov_agent.ini
etc/neutron/rootwrap.d/debug.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/dhcp.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/dibbler.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/ebtables.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/ipset-firewall.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/iptables-firewall.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/l3.filters etc/neutron/rootwrap.d
etc/neutron/rootwrap.d/linuxbridge-plugin.filters
etc/neutron/rootwrap.d/openvswitch-plugin.filters
etc/policy.json etc/neutron
etc/rootwrap.conf etc/neutron
