#!/bin/sh

set -e 

if [ "$1" = "configure" ]
then
    if ! getent group neutron > /dev/null 2>&1
    then
        addgroup --system neutron >/dev/null
    fi
    if ! getent passwd neutron > /dev/null 2>&1
    then
        adduser --system --home /var/lib/neutron --ingroup neutron --no-create-home --shell /usr/sbin/nologin neutron
    fi

    chown neutron:adm /var/log/neutron
    chmod 0750 /var/log/neutron

    find /etc/neutron -exec chown root:neutron "{}" +
    find /etc/neutron -type f -exec chmod 0640 "{}" + -o -type d -exec chmod 0750 "{}" +

    # Optional rootwrap.d configuration files.
    find /etc/neutron/rootwrap.d -exec chown root:root "{}" +
    find /etc/neutron/rootwrap.d -type f -exec chmod 0644 "{}" + -o -type d -exec chmod 0755 "{}" +

    find /var/lib/neutron -exec chown neutron:neutron "{}" +
    find /var/lib/neutron -type f -exec chmod 0640 "{}" + -o -type d -exec chmod 0750 "{}" +

    # Ensure dnsmasq has needed access as it runs as nobody
    chmod 0755 /var/lib/neutron
    find /var/lib/neutron/dhcp -type f -exec chmod 0644 "{}" + -o -type d -exec chmod 0755 "{}" +

    # NOTE(jamespage): In order to execute unit test in decomposed
    #                  vendor drivers, /etc/neutron must be readable
    #                  other than by root or neutron; limitation of
    #                  access to neutron.conf is sufficient as this
    #                  file contains access details for DB, keystone
    #                  and message bus.
    chmod 0755 /etc/neutron /etc/neutron/policy.d

    if [ -f /etc/sudoers.d/neutron_sudoers ] ; then
        chmod 0440 /etc/sudoers.d/neutron_sudoers
    fi
fi

#DEBHELPER#
